### ISSUE TITLE
L2 Update: New ELSE Statement in J.3 Section of LP5

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#10]
The clinicians realized that we need to provide a care recommendation for individuals who's high-grade event occurred > 25 years ago and they have passed the 'initial intensive surveillance period'. Prior to this update, clinicians caring for these women would not have been presented with the following: Continued surveillance at 3-year intervals beyond 25 years is acceptable for as long as the patient's life expectancy and ability to be screened are not significantly compromised by serious health issues.

See the update in BOLD text.

2._ After the initial intensive surveillance period, continued surveillance at 3-year intervals is recommended for at least 25 years after treatment of high-grade histology (histologic HSIL, CIN 2, CIN 3, or AIS) or high-grade cytology (HSIL, AGC, or persistent ASC-H) even if this is beyond the age of 65 years (BII)._

IF MOST RECENT ‘treatment for high-grade histology or cytology’ <=25 years ago
AND ‘initial intensive surveillance period’
DISPLAY In patients treated for histologic or cytologic HSIL, after the initial intensive surveillance period, continued surveillance at 3-year intervals is recommended for at least 25 years after treatment of high-grade histology (histologic HSIL, CIN 2, CIN 3, or AIS) or high-grade cytology (HSIL, AGC, or persistent ASC-H) even if this is beyond the age of 65 years (BII). When patients with a history of treated high-grade histology or cytology reach the age of 65 years, if they have completed the initial 25-year surveillance period, continued surveillance at 3-year intervals is acceptable and may continue as long as the patient is in reasonably good health (BIII). Discontinuation of screening is recommended if a patient has a limited life expectancy. Management according to the highest-grade abnormality found on histology or cytology is recommended.

**ELSE
IF MOST RECENT ‘treatment for high-grade histology or cytology’ > 25 years ago
AND ‘initial intensive surveillance period’

DISPLAY: Continued surveillance with HPV testing or cotesting at 3-year intervals for at least 25 years is recommended after treatment and initial post-treatment management of histologic HSIL, CIN 2, CIN 3, or AIS. Continued surveillance at 3-year intervals beyond 25 years is acceptable for as long as the patient's life expectancy and ability to be screened are not significantly compromised by serious health issues.**

**Comment by mickohanlon23** [comment]
My guess would be that this situation would be rare, since it would involve needing to identify a treatment procedure and the abnormal test results that led to the treatment both from >25 years ago. But definitely makes sense to add in order to be comprehensive!

**Comment by mickohanlon23** [comment]
I made the change in this commit: https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commit/4654925d36003b37c6d5dc5c5cbef75ac6f12ad3.

In general I will make any changes that arise from the Issues you just submitted in the `l2-updates-april-may` branch of this repository (https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commits/l2-updates-april-may). This way we can review them all together as one larger pull request before merging them into our `main` branch. That link shows all of the commits on that branch, if you are curious for tracking. I will try to align the names with the name of the Issue you submit, including the Issue #, so that the code change and the Issue are automatically linked.

I will close out the Issues after I make the change and it seems like there is no follow-up discussion, however, feel free to re-open any Issues as necessary.

**Comment by ssebast2** [comment]
Sounds good. Thanks Mick!
