### ISSUE TITLE
MedicationDispense: Fine-tuning the preferred dateTime

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#15]
We noticed that 'whenHandedOver' and 'whenPrepared' may have been included in the L3. 'whenHandedOver' is the dateTime that we are most interested in.

Why was 'whenPrepared' included? That dateTime is not relevant if the patient never picked it up.

If 'whenPrepared' is retained and the dateTime for both 'whenPrepared' and 'whenHandedOver' is present in the patient data, have you included a business rule that "considers" 'whenHandedOver' and disregards 'whenPrepared'?

**Comment by mickohanlon23** [comment]
Essentially, yes! This is another situation where `whenPrepared` is used as the backup date if `whenHandedOver` does not exist (neither are required).

There are two places this is used:

**1) Populating the date in the Dashboard:**
This is where `whenPrepared` is used as a backup if `whenHandedOver` does not exist. I think it is appropriate to keep this, since it would be more helpful to see _a_ date associated with the medication as opposed to no date at all.

**2) Medication Lookback Period:**
When "looking back" for a MedicationDispense our code only requires one of either `whenHandedOver` or `whenPrepared` to fall in the lookback period (the default value for this period is 6 months for medications). So it is not explicitly "disregarded" but if they both exist, the Medication Dispense would be included as long as `whenHandedOver` is within the lookback. Since we only use it here in the context of "looking back", I don't believe we need to add any extra business rule than that, since MedicationDispense has an invariant that "whenHandedOver cannot be before whenPrepared" (See https://build.fhir.org/medicationdispense-definitions.html#MedicationDispense). Therefore we would not have to worry about a situation where something is improperly included in the lookback because of its `whenPrepared` date.

Let me know if this makes sense, or if you do in fact think we need to change the way we're handling either of the above. Happy to to discuss this one over a call if need be!

**Comment by ssebast2** [comment]
That makes sense. Thanks for the explanation!

**Comment by ssebast2** [comment]
Let me talk to Rose about this one and I will circle back.
