### ISSUE TITLE
QuestionnaireResponse: Please confirm attributes

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#16]
Is this the list of attributes included in the L3?

-QuestionnaireResponse.status
-QuestionnaireResponse.authored
-QuestionnaireResponse.linkId
-QuestionnaireResponse.answer
-QuestionnaireResponse.item

**Comment by mickohanlon23** [comment]
I am currently in the process of working on our QuestionnaireResponse processing, so I will keep this issue open as this is still a work in progress. But that list appears to be comprehensive as of now, in terms of data we will be "requiring" our QuestionnaireResponses to have (as I mentioned in the Data Requirements spreadsheet, the term data requirements doesn't _exactly_ apply here, since this is more of our internal representation of a clinician's answers and they would likely be converted to a different resource before being "written back" to an EHR).

I'll invite @dwwinters to chime in with any other insights, since he has also been doing some work recently with our questionnaire handling.

Note that the last three elements are actually sub-elements of `item`. So the correct list is as follows:

QuestionnaireResponse.status
QuestionnaireResponse.authored
QuestionnaireResponse.item.linkId
QuestionnaireResponse.item.answer
QuestionnaireResponse.item.item

**Comment by mickohanlon23** [comment]
Closing this issue as the original question was answered, and the data requirements spreadsheet has already been created.
