### ISSUE TITLE
HPV Immunization: Attributes

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#17]
What attributes are in the L3 to support the dashboard display?

 - code
 - occuranceDateTime?
 - recordedDateTime?

I assume that we display the HPV vaccination (code) and a date of the immunization.

**Comment by mickohanlon23** [comment]
- vaccineCode
- status
- occurrence[x]
- expirationDate

So mainly what you listed with the addition of status and expirationDate. I don't believe recordedDateTime is relevant, especially since occurrence[x] is required to be present for an [Immunization Resource](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-immunization.html). But feel free to correct me if I'm wrong or if there are additional elements I should be adding to the list :)

**Comment by ssebast2** [comment]
I agree with including .vaccineCode, .status, and .occurrence[x]. I know that the expirationDate is not required for the CDS. Unless it is explicitly required by one of the eCQMs, I believe it can be deleted.

**Comment by mickohanlon23** [comment]
@ssebast2 - As far as being required by the CDS, HPV Immunizations aren't actually used in any of the current logic, so the elements I listed above were only elements that we decided could be nice to include in the Dashboard display.

2 Questions:
1. Should I remove Expiration Date from the Dashboard display
2. Currently, we just display the `.status` element on the Dashboard, but we don't actually use it to filter the list of vaccines. Should we use the status element to filter out any vaccine that is not "completed" (I think this makes sense since status is required by a [US Core Immunization](http://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-immunization.html) and the other two possible codes in the [value set](http://hl7.org/fhir/R4/valueset-immunization-status.html) (entered-in-error, and not-done) would invalidate the immunization?

**Comment by ssebast2** [comment]
@mickohanlon23 - 
1. Yes, please remove Expiration Date from the Dashboard display
2. Yes, .status=completed makes the most sense. So, if .status is found in the patient record - it should equal completed.

Thanks Mick!

**Comment by mickohanlon23** [comment]
Commit https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/commit/65b51337bfd30c4c86aa4f70ba1f093cafab82e7 (1) removes ExpirationDate from the Dashboard display, and (2) restricts Immunizations populated on the Dashboard to those with a `completed` status. 

Testing was also added to make sure that the CQL code is properly looking for the `Immunization.status` element.
