### ISSUE TITLE
Condition: Attributes for Dx of Cervical or Vaginal Lesion

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#18]
Mick mentioned that the L3 does not have any date attributes. How can that be? We need to know when it was recorded and see if it occurred within 24 hours? Plus we need to display the date in the dashboard of when the dx was recorded/active.

We have the following listed in the DER:
- code
- onsetDateTime
- recordedDate
- clinicalStatus (unrestricted based on 5/10 discussion)
- verificationStatus = unconfirmed, provisional, differential, confirmed
- abatement attributes will be discussed with pilot site before adding the L3 code

**Comment by mickohanlon23** [comment]
When did I mention there were no date attributes for Diagnosis of Cervical or Vaginal Lesion? I may have misspoke. We currently display the `recordedDate` in the Dashboard, and check for both the `onset[x]` and the `recordedDate` when determining whether the symptoms happened in the past 24 hours.

We don't currently have the `verificationStatus` attribute constrained, but I can add them. I was thinking instead of forcing verificationStatus to be present with one of those 4 values, we could simply ignore the Condition if `verificationStatus` existed with a value of `refuted` or `entered-in-error`, since `verificationStatus` is not required.

**Comment by ssebast2** [comment]
I understood you to say that you don't look for any dates a/w with this DE during the last call we had with Rose, you, Dave and I. What you described about the recordedDate and onset[x] sounds good. 

Your suggestion about ignoring verificationStatus if it equals refuted or entered-in-error sounds good also. Thanks!

**Comment by mickohanlon23** [comment]
@ssebast2:

**Dates** 
I may have been mixing up the use of dates for the dashboard with the use of dates for the actual logic. Sorry if that was confusing. The date attributes for this DE are handled similarly to how other Conditions in the Dashboard use dates. I will leave this as is.

**`verificationStatus` constraint**
verificationStatus for Dx of Cervical or Vaginal Lesion was constrained in the same way that all the other Conditions were recently constrained, according to Issue https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/11. This also aligns with what is written in my comment above.

**Comment by mickohanlon23** [comment]
@ssebast2  I will resolve this Issue as it seems like the main two points have been addressed. However, feel free to re-open if you see any outstanding issues.
