### ISSUE TITLE
Condition: Dx of In Utero Exposure to DES

### ISSUE THREAD

**Issue by ssebast2** [ccsm-cds-tools/ccsm-cds-with-tests#19]
Mick entered a comment in the DER that the only DE being used in the CDS is code. How can that be? Aren't we displaying a date next to the entry on the dashboard? Will you be including the constrained verificationStatus' that we agreed on on 5/10?

**Comment by mickohanlon23** [comment]
Sorry, I should have been clearer by that comment. `code` is the only element that is needed by the actual logic for a DES Exposure Condition, since the logic only needs a simple yes/no to "Were you exposed to DES?". But you're correct, when we display this in the dashboard, we display all of the same elements as we do for other Conditions:
- code
- clinicalStatus
- onset[x]
- recordedDate

Would you like me to add the constraints for `verificationStatus` to the DES Exposure queries? Should these be applied to all conditions, or just this one and the Cervical Vaginal Lesions Condition mentioned in https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/issues/18?

**Comment by mickohanlon23** [comment]
I added constraints for `verificationStatus` to the DES Exposure queries, since we agreed in Issue #11 to add this constraint to all conditions. 

Between the addition of the `verificationStatus` constraint and the clarification of the data elements used in the dashboard in my original comment, I believe all concerns about this issue were addressed. I will close this out, but feel free to re-open if there are further issues.
